# Generated by Django 4.2.15 on 2024-08-07 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="category_image/%Y/%m/%d/"
                    ),
                ),
                ("keywords", models.CharField(max_length=100)),
                ("popularity", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("image", models.ImageField(upload_to="course/%Y/%m/%d/")),
                (
                    "long_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="course/%Y/%m/%d/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="videos/course/%Y/%m/%d/"
                    ),
                ),
                ("price", models.CharField(max_length=20)),
                ("total_enroled", models.IntegerField(default=0)),
                ("duration", models.CharField(max_length=20)),
                ("features", models.SlugField(max_length=200)),
                ("is_featured", models.BooleanField(default=False)),
                ("keywords", models.CharField(max_length=100)),
                ("popularity", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="course.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="videos/lession/%Y/%m/%d/"
                    ),
                ),
                (
                    "resource",
                    models.FileField(
                        blank=True, null=True, upload_to="files/lession/%Y/%m/%d/"
                    ),
                ),
                ("duration", models.CharField(max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.chapter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("payment_info", models.TextField()),
                ("is_complete", models.BooleanField(default=False)),
                ("in_competition", models.BooleanField(default=False)),
                ("mark", models.IntegerField(default=0)),
                ("bonus_mark", models.IntegerField(default=0)),
                ("show_in_profile", models.BooleanField(default=True)),
                ("position", models.IntegerField(default=0)),
                ("show_position_in_profile", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_chapters",
                    models.ManyToManyField(
                        related_name="completed_chapters", to="course.chapter"
                    ),
                ),
                (
                    "completed_lessions",
                    models.ManyToManyField(
                        related_name="completed_lessions", to="course.lession"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.course"
            ),
        ),
    ]
