# Generated by Django 4.2.15 on 2024-08-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lession',
            new_name='Lesson',
        ),
    ]
