# Generated by Django 4.2.15 on 2024-08-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_total_enroled_course_total_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='completed_lessions',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='completed_lessons',
            field=models.ManyToManyField(related_name='completed_lessons', to='course.lesson'),
        ),
    ]
