# Generated by Django 4.2.15 on 2024-08-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="videos/competition/%Y/%m/%d/"
            ),
        ),
    ]
